### ISSUE TITLE
Adding FSharp

### ISSUE THREAD

**Issue by ShalokShalom** [helix-editor/tspm#1]
Hi 🌻 

I added this line to grammars.nix

```fs
fsharp.nsidorenco = tspm.grammar { meta.license = lib.licenses.mit; };
```

And then ran this line, the flags are required by the command to run;

> sudo nix run --extra-experimental-features nix-command --extra-experimental-features flakes .#lock -- nsidorenco fsharp

And then this

![image](https://user-images.githubusercontent.com/6344099/217959459-3e232a1d-09aa-46ff-9c11-0f4ce8901c17.png)

**Comment by the-mikedavis** [comment]
I can't reproduce this. I added that line, ran `nix run .#lock nsidorenco fsharp` and then `nix flake check` and it all builds and checks correctly. I'm running Nix 2.12.0 with flakes enabled. You should also not need `sudo` to run `nix`: something may be amiss with your Nix installation.

Besides that though, this repo is not seeking contributions at the moment: there is a PR that the tree-sitter author is working on that will enable packaging grammars as WASM which will simplify a lot of what TSPM was looking to solve and will probably lead to a big refactor.

If you're looking to add F# support to Helix, check out the [guide doc](https://docs.helix-editor.com/master/guides/adding_languages.html). Adding a new language to Helix doesn't need any changes in this repository.

**Comment by ShalokShalom** [comment]
Nix 2.13.2 with the default settings. 
Thanks a lot 

I will look at these docs. You might wanna change the Readme of this repo, since it's saying, that "this is how you package new grammars".
